FlowerShop/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('clear/', views.cart_clear, name='cart_clear'),
]

FlowerShop/cart/models.py
from django.db import models

# Create your models here.

FlowerShop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput)

FlowerShop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from .cart import Cart
from .forms import CartAddProductForm
from shop.models import Product
from shop.recommender import Recommender


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    if cart:
        return redirect("cart:cart")
    return redirect('shop:products')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'], 'override': True})
    r = Recommender()
    cart_products = [item['product'] for item in cart]
    recommended_products = r.suggest_products_for(cart_products, max_results=4)
    context = {
        'cart': cart,
        'recommended_products': recommended_products
    }
    return render(request, 'cart/detail.html', context)


def cart_clear(request):
    cart = Cart(request=request)
    cart.clear()
    return redirect("shop:products")

FlowerShop/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
Your shopping cart
{% endblock %}

{% block content %}
<h1>Your shopping cart</h1>
<table class="cart">
    <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        {% for item in cart %}
        {% with product=item.product %}
        <tr>
            <td>
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}
                {% else %}{% static "img/no_image.png" %}{% endif %}">
                </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
                <form action="{% url "cart:cart_add" product.id %}" method="post">
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.override }}
                    <input type="submit" value="Update">
                    {% csrf_token %}
                </form>
            </td>
            <td>
                <form action="{% url "cart:cart_remove" product.id %}" method="post">
                    <input type="submit" value="Remove">
                    {% csrf_token %}
                </form>
            </td>
            <td class="num">${{ item.price }}</td>
            <td class="num">${{ item.total_price }}</td>
        </tr>
        {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr>
    </tbody>
</table>

{% if recommended_products %}
    <div class="recommendations cart">
        <h3>People who bought this also bought</h3>
        {% for p in recommended_products %}
        <div class="item">
            <a href="{{ p.get_absolute_url }}">
                <img src="{% if p.image %}{{ p.image.url }}{% else %}{% static 'images/no_image.png' %}{% endif %}">
            </a>
            <p><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></p>
        </div>
        {% endfor %}
    </div>
{% endif %}

<p class="text-right">
    <a href="{% url 'cart:cart_clear' %}" class="btn btn-danger">Clear Cart</a>
    <a href="{% url 'shop:products' %}" class="button light">Continue Shopping</a>
    {% if user.profile.address %}
        <a href="{% url 'orders:order_create' %}" class="button">Checkout</a>
    {% else %}
        <a href="{% url 'users:address_create' %}?next={{ request.path|urlencode }}"" class="button">Create Address</a>
    {% endif %}
</p>
{% endblock %}