FlowerShop/users/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views

from . import views


app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/update/', views.profile_update, name='profile_update'),

    path('address/', views.AddressListView.as_view(), name='address_list'),
    path('address/create/', views.AddressCreateView.as_view(), name='address_create'),
    path('address/<int:pk>/', views.AddressDetailView.as_view(),
         name='address_detail'),
    path('address/update/<int:pk>/',
         views.AddressUpdateView.as_view(), name='address_update'),
    path('address/delete/<int:pk>/',
         views.AddressDeleteView.as_view(), name='address_delete'),

]

FlowerShop/users/templates/users/address/create.html
{% extends "shop/base.html" %} 
{% load crispy_forms_tags %} 
{% block content %}

<!-- Sidebar -->
<div id="sidebar">
    <ul>
        <li>
            <a href="{% url 'users:profile' %}" class="btn btn-secondary"
                >Profile Overview</a
            >
        </li>
        <li>
            <a href="{% url 'users:profile_update' %}" class="btn btn-secondary"
                >Profile Information</a
            >
        </li>
        <li><a href="{% url 'orders:orders' %}" class="btn btn-secondary">My Orders</a></li>
        <li><a href="#" class="btn btn-secondary">Favorite Products</a></li>
        <li><a href="{% url 'users:address_list' %}" class="btn btn-secondary">Addresses</a></li>
        <li>
            <a href="{% url 'users:logout' %}" class="btn btn-secondary">Logout</a>
        </li>
    </ul>
</div>

<!-- Create Address -->
<h1>Create  Address</h1>
<div class="row">
    <div class="col col-8">
        <form method="post">
            <p>{{ form|crispy }}</p>
            <p><input type="submit" value="Add Address" name="address"/></p>
            {% csrf_token %}
        </form>
    </div>
</div>
{% endblock content %}

FlowerShop/users/templates/users/address/delete_confirm.html
{% extends "shop/base.html" %} 
{% load crispy_forms_tags %} 
{% block content %}

<!-- Sidebar -->
<div id="sidebar">
    <ul>
        <li>
            <a href="{% url 'users:profile' %}" class="btn btn-secondary"
                >Profile Overview</a
            >
        </li>
        <li>
            <a href="{% url 'users:profile_update' %}" class="btn btn-secondary"
                >Profile Information</a
            >
        </li>
        <li><a href="{% url 'orders:orders' %}" class="btn btn-secondary">My Orders</a></li>
        <li><a href="#" class="btn btn-secondary">Favorite Products</a></li>
        <li><a href="{% url 'users:address_list' %}" class="btn btn-secondary">Addresses</a></li>
        <li>
            <a href="{% url 'users:logout' %}" class="btn btn-secondary">Logout</a>
        </li>
    </ul>
</div>

<!-- Confirm delete -->
<h1>Delete Address</h1>
<div class="row">
    <div class="col col-8">
        <form method="post">
            <h4>Do you want to delete: <div class="disabled">{{ address.address_detail }}</div></h4>
            <p><button class="btn btn-danger" type="submit" name="address"/>Delete Address</button></p>
            <p><a href="{% url 'users:address_detail' address.id %}">Cancel</a></p>
            {% csrf_token %}
        </form>
    </div>
</div>
{% endblock content %}

FlowerShop/users/templates/users/address/detail.html
{% extends "shop/base.html" %} 
{% load crispy_forms_tags %} 
{% block content %}

<!-- Sidebar -->
<div id="sidebar">
    <ul>
        <li>
            <a href="{% url 'users:profile' %}" class="btn btn-secondary"
                >Profile Overview</a
            >
        </li>
        <li>
            <a href="{% url 'users:profile_update' %}" class="btn btn-secondary"
                >Profile Information</a
            >
        </li>
        <li><a href="{% url 'orders:orders' %}" class="btn btn-secondary">My Orders</a></li>
        <li><a href="#" class="btn btn-secondary">Favorite Products</a></li>
        <li><a href="{% url 'users:address_list' %}" class="btn btn-secondary">Addresses</a></li>
        <li>
            <a href="{% url 'users:logout' %}" class="btn btn-secondary">Logout</a>
        </li>
    </ul>
</div>

<!-- Address -->
<h1>Address</h1>
<br>
<div class="row">
    <div class="col-8">

        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                {{ address.address_detail }}
            </li>
            <li class="list-group-item">
                {{ address.state }}
            </li>
            <li class="list-group-item">
                {{ address.city }}
            </li>
            <li class="list-group-item">
                {{ address.postal_code }}
            </li>
            <li class="list-group-item">
                {{ address.phone_number }}
            </li>
        </ul>
        <br>
        <p><a href="{% url 'users:address_update' address.id %}">Update Address</a></p>
        <p><a href="{% url 'users:address_delete' address.id %}">Delete Address</a></p>
    </div>
<div class="col-2"></div>



{% endblock content %}

FlowerShop/users/templates/users/address/list.html
{% extends "shop/base.html" %} 
{% load crispy_forms_tags %} 
{% block content %}

<!-- Sidebar -->
<div id="sidebar">
    <ul>
        <li>
            <a href="{% url 'users:profile' %}" class="btn btn-secondary"
                >Profile Overview</a
            >
        </li>
        <li>
            <a href="{% url 'users:profile_update' %}" class="btn btn-secondary"
                >Profile Information</a
            >
        </li>
        <li><a href="{% url 'orders:orders' %}" class="btn btn-secondary">My Orders</a></li>
        <li><a href="#" class="btn btn-secondary">Favorite Products</a></li>
        <li><a href="{% url 'users:address_list' %}" class="btn btn-secondary">Addresses</a></li>
        <li>
            <a href="{% url 'users:logout' %}" class="btn btn-secondary">Logout</a>
        </li>
    </ul>
</div>

<!-- Addresses -->
<h1>My Addresses</h1>
<div>
    <ul class="list-group list-group-flush">
        {% if addresses %}
            {% for address in addresses  %}
                <li class="list-group-item"><a href="{% url 'users:address_detail' address.id %}">{{ address.address_detail }}</a></li>
            {% endfor %}   
        {% else %}
            You have not entered any addresses yet.
        {% endif %}
    </ul>
    <p><a href="{% url 'users:address_create' %}">Create New Address</a></p>
</div>
{% endblock content %}

FlowerShop/users/templates/users/address/update.html
{% extends "shop/base.html" %} 
{% load crispy_forms_tags %} 
{% block content %}

<!-- Sidebar -->
<div id="sidebar">
    <ul>
        <li>
            <a href="{% url 'users:profile' %}" class="btn btn-secondary"
                >Profile Overview</a
            >
        </li>
        <li>
            <a href="{% url 'users:profile_update' %}" class="btn btn-secondary"
                >Profile Information</a
            >
        </li>
        <li><a href="{% url 'orders:orders' %}" class="btn btn-secondary">My Orders</a></li>
        <li><a href="#" class="btn btn-secondary">Favorite Products</a></li>
        <li><a href="{% url 'users:address_list' %}" class="btn btn-secondary">Addresses</a></li>
        <li>
            <a href="{% url 'users:logout' %}" class="btn btn-secondary">Logout</a>
        </li>
    </ul>
</div>

<!-- Update Address -->
<h1>Update Address</h1>
<div class="row">
    <div class="col col-8">
        <form method="post">
            <p>{{ form|crispy }}</p>
            <p><input type="submit" value="Update Address" name="address"/></p>
            {% csrf_token %}
        </form>
    </div>
</div>
{% endblock content %}