FlowerShop/users/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views

from . import views


app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/update/', views.profile_update, name='profile_update'),

    path('address/', views.AddressListView.as_view(), name='address_list'),
    path('address/create/', views.AddressCreateView.as_view(), name='address_create'),
    path('address/<int:pk>/', views.AddressDetailView.as_view(),
         name='address_detail'),
    path('address/update/<int:pk>/',
         views.AddressUpdateView.as_view(), name='address_update'),
    path('address/delete/<int:pk>/',
         views.AddressDeleteView.as_view(), name='address_delete'),

]

FlowerShop/users/templates/users/dashboard.html
{% extends "shop/base.html" %}

{% load crispy_forms_tags %}


{% block title %}
Dashboard
{% endblock title %}

{% block content %}
<div id="sidebar">
    <ul>
        <li><a href="{% url 'users:profile' %}" class="btn btn-secondary">Profile Information</a></li>
        <li><a href="#" class="btn btn-secondary">My Orders</a></li>
        <li><a href="#" class="btn btn-secondary">Favorite Products</a></li>
        <li><a href="{% url 'users:logout' %}" class="btn btn-secondary">Logout</a></li>
    </ul>
</div>
<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
            <h2 class="account-heading">{{ user.username }}</h2>
            <p class="text-secondary">{{ user.email }}</p>
        </div>

    </div>
</div>
{% endblock content %}

FlowerShop/users/templates/users/login.html
{% extends "shop/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log In</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Login</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{% url 'users:register' %}">Sign Up Now</a>
        </small>
    </div>
</div>
{% endblock content %}

FlowerShop/users/templates/users/logout.html
{% extends "shop/base.html" %}

{% block content %}
<h2>You have been logged out</h2>
<div class="border-top pt-3">
    <small class="text-muted">
        <a href="{% url 'users:login' %}">Log In Again</a>
    </small>
</div>
{% endblock content %}

FlowerShop/users/templates/users/profile.html
{% extends "shop/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<!-- Sidebar -->
<div id="sidebar">
    <ul>
        <li>
            <a href="{% url 'users:profile' %}" class="btn btn-secondary"
                >Profile Overview</a
            >
        </li>
        <li>
            <a href="{% url 'users:profile_update' %}" class="btn btn-secondary"
                >Profile Information</a
            >
        </li>
        <li><a href="{% url 'orders:orders' %}" class="btn btn-secondary">My Orders</a></li>
        <li><a href="#" class="btn btn-secondary">Favorite Products</a></li>
        <li><a href="{% url 'users:address_list' %}" class="btn btn-secondary">Addresses</a></li>
        <li>
            <a href="{% url 'users:logout' %}" class="btn btn-secondary">Logout</a>
        </li>
    </ul>
</div>

<!-- User Information -->
<div class="content-section">
    <div class="media m-1">
            <img
            class="rounded-circle account-img"
            src="{{ user.profile.image.url }}"
            />
            <div class="media-body">
            <h2 class="account-heading">{{ user.username }}</h2>
            <p class="text-secondary">{{ user.email }}</p>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col col-2"></div>
        <div class="col col-5">
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><b>E-mail</b>: {{ user.email }}</li>
                <li class="list-group-item"><b>First Name</b>: {{ user.first_name }}</li>
                <li class="list-group-item"><b>Last Name</b>: {{ user.last_name }}</li>
            </ul>
        </div>
        <div class="col col-5">
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><b>Password</b>: *****</li>
            </ul>
        </div>
    </div>
</div>

<!-- Last Orders -->
<div class="content-section">
    <div class="row">
        <div class="col col-2"></div>
        <div class="col col-8">
            {% if last_orders %}
                {% for order in last_orders %}
                    <a href="{% url 'orders:order_detail' order.id %}" class="btn btn-info">order_id: {{ order.id }}</a>
                    <ul>
                        {% if order.get_order_items %}
                            {% with order.get_order_items as order_items %}
                                {% for item in order_items %}
                                    <li>
                                        item {{ forloop.counter }}: <a href="{{ item.product.get_absolute_url }}">{{ item.product }}</a>
                                    </li>
                                {% endfor %}
                            {% endwith %}
                        {% endif %}
                    </ul>
                {% endfor %}
            {% else %}
                You have not bought anything yet
            {% endif %}
        </div>
        <div class="col col-2"></div>
    </div>
</div>
{% endblock content %}

FlowerShop/users/templates/users/register.html
{% extends "shop/base.html" %}

{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join Today</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Sign Up</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{% url 'users:login' %}">Sign In</a>
        </small>
    </div>
</div>
{% endblock content %}

FlowerShop/users/templates/users/update.html
{% extends "shop/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<!-- Sidebar -->
<div id="sidebar">
    <ul>
        <li>
            <a href="{% url 'users:profile' %}" class="btn btn-secondary"
                >Profile Overview</a
            >
        </li>
        <li>
            <a href="{% url 'users:profile_update' %}" class="btn btn-secondary"
                >Profile Information</a
            >
        </li>
        <li><a href="{% url 'orders:orders' %}" class="btn btn-secondary">My Orders</a></li>
        <li><a href="#" class="btn btn-secondary">Favorite Products</a></li>
        <li><a href="{% url 'users:address_list' %}" class="btn btn-secondary">Addresses</a></li>
        <li>
            <a href="{% url 'users:logout' %}" class="btn btn-secondary">Logout</a>
        </li>
    </ul>
</div>
<!-- Update Information Forms -->
<div class="content-section">
    <div class="media m-1">
            <img
            class="rounded-circle account-img"
            src="{{ user.profile.image.url }}"
            />
            <div class="media-body">
            <h2 class="account-heading">{{ user.username }}</h2>
            <p class="text-secondary">{{ user.email }}</p>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col col-2"></div>
        <!-- Change Information Modal -->
        <div class="col col-5">
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><b>E-mail</b>: {{ user.email }}</li>
                <li class="list-group-item"><b>First Name</b>: {{ user.first_name }}</li>
                <li class="list-group-item"><b>Last Name</b>: {{ user.last_name }}</li>
            </ul>
            <button type="submit" value="test" class="btn btn-primary" data-toggle="modal" data-target="#ChangeInformation">
                Change Information
            </button>
        </div>
        <div class="modal fade" id="ChangeInformation" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                        <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Change Information</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                    <div class="modal-body">
                        <form class="order-form" method="post" action="{% url 'users:profile_update' %}">
                            <p>{{ user_form|crispy }}</p>
                            <p><input type="submit" value="Change Info" name="info"/></p>
                            {% csrf_token %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- Change Password Modal -->
        <div class="col col-5">
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><b>Password</b>: *****</li>
            </ul>
            <button type="submit" value="test" class="btn btn-primary" data-toggle="modal" data-target="#ChangePassword" >
                Change Password
            </button>
        </div>
        <div class="modal fade" id="ChangePassword" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                        <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Change Password</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                    <div class="modal-body">
                        <form class="order-form" method="post">
                            <p>{{ pass_form|crispy }}</p>
                            <p><input type="submit" value="Change Password" name="password"/></p>
                            {% csrf_token %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}