FlowerShop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.OrderListView.as_view(), name="orders"),
    path('<int:pk>/', views.OrderDetailView.as_view(), name="order_detail"),
    path('create/', views.order_create, name='order_create'),
]

FlowerShop/orders/models.py
from django.db import models
from shop.models import Product
from django import forms
from users.models import Profile, Address


class Order(models.Model):
    customer = models.ForeignKey(
        Profile, verbose_name="customer", on_delete=models.CASCADE)

    # total_products_price = models.IntegerField()
    # discount = models.IntegerField()
    # price_after_discount = models.IntegerField()      # sum of total_products_price and discount
    # shipment_price = models.IntegerField()
    # total_vat = models.IntegerField()
    # total_bill_price = models.IntegerField()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)

    @property
    def get_order_items(self):
        items = [i for i in OrderItem.objects.filter(order=self.pk)]

        return items

    def __str__(self):
        return f'Order {self.id}'


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

FlowerShop/orders/forms.py
from django import forms
from .models import Order, Profile, Address


class OrderCreateForm(forms.ModelForm):

    def __init__(self, customer, address, *args, **kwargs):
        super(OrderCreateForm, self).__init__(*args, **kwargs)
        self.customer = customer
        self.address = address

    def save(self, commit=True):
        instance = super(OrderCreateForm, self).save(commit=False)
        if not instance.pk:
            instance.customer = self.customer
            instance.address = self.address
        if commit:
            instance.save()
        return instance

    class Meta:
        model = Order
        fields = ['id']

FlowerShop/orders/views.py
from django.shortcuts import render, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView
from django.contrib import messages


from .models import OrderItem, Order
from .forms import OrderCreateForm
from .tasks import order_created
from cart.cart import Cart


@login_required
def order_create(request):
    cart = Cart(request)

    if request.method == 'POST' and cart:
        customer = request.user.profile
        address = request.user.profile.address
        form = OrderCreateForm(customer, address, request.POST, request.FILES)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            # clear the cart
            cart.clear()
            order_created.delay(order.id)
            print('hello')
            return render(request,
                          'orders/order/created.html',
                          {'order': order})
    elif request.method == "POST" and not cart:
        if request.user.profile.address:
            print('no order item')
            customer = request.user.profile
            address = request.user.profile.address

            form = OrderCreateForm(customer, address)
            messages.error(request=request, message="No Item in Order")
            return render(request,
                          'orders/order/create.html',
                          {'cart': cart, 'form': form})
    else:
        if request.user.profile.address:
            customer = request.user.profile
            address = request.user.profile.address

            form = OrderCreateForm(customer, address)

    return render(request,
                  'orders/order/create.html',
                  {'cart': cart, 'form': form})


class OrderListView(LoginRequiredMixin, ListView):
    model = Order
    template_name = "orders/order/list.html"
    context_object_name = "orders"

    def get_queryset(self):
        return self.model.objects.filter(customer=self.request.user.profile)


class OrderDetailView(LoginRequiredMixin, DetailView):
    model = Order
    template_name = "orders/order/detail.html"
    context_object_name = "order"

    def get_queryset(self):
        return self.model.objects.filter(customer=self.request.user.profile)

FlowerShop/orders/templates/orders/order/create.html
{% extends "shop/base.html" %}


{% block title %}
 Checkout
{% endblock %}

{% block content %}

    
    <h1>Checkout</h1> 

    
    <div class="order-info">
        <h3>Your Order</h3>
        <ul>
            {% for item in cart %}
            <li>
                {{ item.quantity }}x {{ item.product.name }}
                <span>${{ item.total_price }}</span>
            </li>
            {% endfor %}
        </ul>
        <p>Total: ${{ cart.get_total_price }}</p>
    </div>
    <div class="row">
        <div class="col col-6">
            <form method="POST" class="order-form">
                {{ form.as_p }}
                <p><input type="submit" value="Place Order"></p>
                {% csrf_token %}
            </form>
        </div>
        
        <div class="col col-6 order-info">
            <ul>
                <li>{{ form.customer.user.username }}</li>
                <li>{{ form.address.address_detail }}</li>
                <li>{{ form.address.phone }}</li>
                <li>{{ form.address.postal_code }}</li>
                <li>{{ form.address.city }}</li>
            </ul>
        </div>
    </div>
{% endblock  %}

FlowerShop/orders/templates/orders/order/created.html
{% extends "shop/base.html" %}

{% block title %}
  Thank You
{% endblock %}

{% block content %}
  <h1>Thank You</h1>
  <p>Your Order has been successfully completed. Your order number is
    <strong>{{ order.id }}</strong>.</p>
{% endblock %}
{% block test %}

{% endblock test %}

FlowerShop/orders/templates/orders/order/detail.html
{% extends "shop/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<!-- Sidebar -->
<div id="sidebar">
    <ul>
        <li>
            <a href="{% url 'users:profile' %}" class="btn btn-secondary"
                >Profile Overview</a
            >
        </li>
        <li>
            <a href="{% url 'users:profile_update' %}" class="btn btn-secondary"
                >Profile Information</a
            >
        </li>
        <li><a href="{% url 'orders:orders' %}" class="btn btn-secondary">My Orders</a></li>
        <li><a href="#" class="btn btn-secondary">Favorite Products</a></li>
        <li><a href="{% url 'users:address_list' %}" class="btn btn-secondary">Addresses</a></li>
        <li>
            <a href="{% url 'users:logout' %}" class="btn btn-secondary">Logout</a>
        </li>
    </ul>
</div>

<!-- Order Details -->
<div class="list-group">
    
    {% if order %}
        <h2>{{ order }}</h2>
        <h4>Items</h4>
        {% for order_item in order.get_order_items %}                
            <a href="{{ order_item.product.get_absolute_url }}" class="list-group-item list-group-item-action list-group-item-dark">{{ order_item.product }}</a>
            
        {% endfor %}
    {% endif %}
            
</div>



{% endblock content %}

FlowerShop/orders/templates/orders/order/list.html
{% extends "shop/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<!-- Sidebar -->
<div id="sidebar">
    <ul>
        <li>
            <a href="{% url 'users:profile' %}" class="btn btn-secondary"
                >Profile Overview</a
            >
        </li>
        <li>
            <a href="{% url 'users:profile_update' %}" class="btn btn-secondary"
                >Profile Information</a
            >
        </li>
        <li><a href="{% url 'orders:orders' %}" class="btn btn-secondary">My Orders</a></li>
        <li><a href="#" class="btn btn-secondary">Favorite Products</a></li>
        <li><a href="{% url 'users:address_list' %}" class="btn btn-secondary">Addresses</a></li>
        <li>
            <a href="{% url 'users:logout' %}" class="btn btn-secondary">Logout</a>
        </li>
    </ul>
</div>

<!-- Orders -->
<h1>My Orders</h1>
<div class="content-section">
    <div class="row">
        <div class="col col-8">
            {% if orders %}
                {% for order in orders %}
                    <div class="btn btn-info disabled">order_id: {{ order.id }}</div> ---- <a href="{% url 'orders:order_detail' order.id %}">Detail</a>
                    <ul>
                        {% if order.get_order_items %}
                            {% with order.get_order_items as order_items %}
                                {% for item in order_items %}
                                    <li>
                                        item {{ forloop.counter }}: <a href="{{ item.product.get_absolute_url }}">{{ item.product }}</a>
                                    </li>
                                {% endfor %}
                            {% endwith %}
                        {% endif %}
                    </ul>
                {% endfor %}
            {% else %}
                You have not bought anything yet
            {% endif %}
        </div>
        <div class="col col-2"></div>
    </div>
</div>
{% endblock content %}